# примеры API-запросов


# создание объявления
POST http://127.0.0.1:5000/advertisements/
content-type: application/json; charset=UTF-8

{
  "title": "Продам автомобиль",
  "description": "Kia Rio, цвет красный",
  "user_id": 1
}

###

# получение объявления
GET http://127.0.0.1:5000/advertisements/1
Content-Type: application/json ; charset=UTF-8

###

# обновление объявления
PATCH http://127.0.0.1:5000/advertisements/1
Content-Type: application/json ; charset=UTF-8

{
  "title": "Продам автомобиль",
  "description": "Kia Rio, цвет зеленый",
}

###

# удаление объявления
DELETE http://127.0.0.1:5000/advertisements/1
Content-Type: application/json ; charset=UTF-8
