# Generated by Django 4.1 on 2022-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('image', models.URLField(max_length=20)),
                ('release_date', models.CharField(max_length=20)),
                ('lte_exists', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
