# Generated by Django 4.1 on 2022-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(),
        ),
    ]
